"""src/ui/pages/forecast.py — Demand forecast page."""
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src.ui.components import kpi_card, page_header, estimate_notice


def render(active_df: pd.DataFrame, forecast_service, building: str) -> None:
    page_header("Forecast", "48–168 hour demand projections with 95% confidence intervals")

    col1, col2, col3 = st.columns(3)
    with col1:
        resource = st.selectbox("Resource", ["energy", "water", "waste"], index=0, key="fc_res")
    with col2:
        all_bldgs = ["ALL"] + sorted(active_df["building"].unique().tolist()) if "building" in active_df.columns else ["ALL"]
        default_idx = all_bldgs.index(building) if building in all_bldgs else 0
        bldg_sel = st.selectbox("Facility", all_bldgs, index=default_idx, key="fc_bldg")
    with col3:
        horizon = st.selectbox("Horizon", [24, 48, 72, 168],
                               format_func=lambda h: f"{h}h ({h//24}d)" if h >= 24 else f"{h}h",
                               index=1, key="fc_horizon")

    bldg_param = None if bldg_sel == "ALL" else bldg_sel

    with st.spinner("Generating forecast…"):
        try:
            fc_df = forecast_service.predict(active_df, resource=resource,
                                              building=bldg_param, horizon_hours=horizon)
            fc_kpis = forecast_service.get_forecast_kpis(fc_df, resource=resource)
        except Exception as e:
            st.error(f"Forecast could not be generated: {e}")
            return

    unit = fc_kpis.get("unit", "")
    k1, k2, k3, k4 = st.columns(4)
    with k1:
        st.markdown(kpi_card("Total Projected", f"{fc_kpis.get('total_predicted', 0):,.1f}", unit),
                    unsafe_allow_html=True)
    with k2:
        st.markdown(kpi_card("Anticipated Peak", f"{fc_kpis.get('peak_predicted', 0):,.1f}", unit),
                    unsafe_allow_html=True)
    with k3:
        pah = fc_kpis.get("peak_alert_hours", 0)
        st.markdown(kpi_card("Peak Alert Hours", str(pah), "hours above 90th percentile",
                             warn=(pah > 0)), unsafe_allow_html=True)
    with k4:
        st.markdown(kpi_card("Projected Cost", f"${fc_kpis.get('projected_cost_usd', 0):,.0f}",
                             "estimated utility expenditure"), unsafe_allow_html=True)

    # ── Main chart ────────────────────────────────────────────────────────────
    if fc_df is not None and not fc_df.empty:
        fig = go.Figure()

        # CI band
        if "upper_95" in fc_df.columns and "lower_95" in fc_df.columns:
            fig.add_trace(go.Scatter(
                x=pd.concat([fc_df["timestamp"], fc_df["timestamp"].iloc[::-1]]),
                y=pd.concat([fc_df["upper_95"], fc_df["lower_95"].iloc[::-1]]),
                fill="toself",
                fillcolor="rgba(0,168,107,0.12)",
                line=dict(color="rgba(255,255,255,0)"),
                name="95% CI",
                showlegend=True,
            ))

        # Forecast line
        fig.add_trace(go.Scatter(
            x=fc_df["timestamp"],
            y=fc_df["predicted_demand"],
            mode="lines",
            name="Predicted demand",
            line=dict(color="#00a86b", width=2.5),
        ))

        # Peak markers
        if "is_peak_forecast" in fc_df.columns:
            peak_df = fc_df[fc_df["is_peak_forecast"]]
            if not peak_df.empty:
                fig.add_trace(go.Scatter(
                    x=peak_df["timestamp"],
                    y=peak_df["predicted_demand"],
                    mode="markers",
                    name="Peak alert",
                    marker=dict(color="#ef4444", size=8, symbol="triangle-up"),
                ))

        bldg_label = bldg_sel if bldg_sel != "ALL" else "All Facilities"
        fig.update_layout(
            height=360,
            margin=dict(l=10, r=10, t=40, b=10),
            hovermode="x unified",
            plot_bgcolor="#ffffff",
            paper_bgcolor="#ffffff",
            title=f"{horizon}h {resource.capitalize()} Forecast — {bldg_label}",
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        )
        fig.update_xaxes(gridcolor="#f1f5f9", title_text="")
        fig.update_yaxes(gridcolor="#f1f5f9", title_text=unit)
        st.plotly_chart(fig, use_container_width=True)

    estimate_notice("Forecast generated by Ridge regression on cyclical demand patterns. "
                    "Actual demand may vary due to weather, occupancy, or equipment events.")

    # Peak time callout
    pt = fc_kpis.get("peak_forecast_time")
    if pt:
        st.markdown(
            f'<div class="accent-card">📌 <b>Predicted peak:</b> {pt} — '
            f'Consider staggering large equipment start times 30 min before this window.</div>',
            unsafe_allow_html=True,
        )
