"""src/ui/pages/reports.py — Sustainability Reports page."""
import pandas as pd
import streamlit as st
from datetime import datetime

from src.ui.components import page_header


def render(active_df: pd.DataFrame, kpis: dict, filtered_anomalies: pd.DataFrame, building: str) -> None:
    page_header("Reports", "Generate presentation-ready sustainability intelligence reports")

    e = kpis.get("energy", {})
    w = kpis.get("water", {})
    r = kpis.get("waste", {})

    crit_count = 0
    high_count = 0
    if not filtered_anomalies.empty and "severity_tier" in filtered_anomalies.columns:
        crit_count = int((filtered_anomalies["severity_tier"] == "CRITICAL").sum())
        high_count  = int((filtered_anomalies["severity_tier"] == "HIGH").sum())

    total_cost = (e.get("estimated_cost_usd", 0)
                  + w.get("estimated_cost_usd", 0)
                  + r.get("estimated_hauling_cost_usd", 0))

    report_text = f"""ECOSYNC RESOURCE INTELLIGENCE — SUSTAINABILITY AUDIT REPORT
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Facility Scope: {building}
================================================================================

EXECUTIVE SUMMARY
-----------------
EcoSync AI detected {crit_count + high_count} priority incidents across facility resources
during the reporting period. Total estimated operational cost: ${total_cost:,.2f} USD.

1. ENERGY PERFORMANCE
----------------------
  Total Consumption ......... {e.get('total_mwh', 0):,.2f} MWh ({e.get('total_kwh', 0):,.0f} kWh)
  Peak Demand ............... {e.get('peak_kw', 0):,.1f} kW (peak facility: {e.get('peak_building', 'N/A')})
  Scope 2 Carbon ............ {e.get('carbon_emissions_tco2e', 0):,.2f} tCO2e
  Off-Hours Baseload ........ {e.get('off_hours_baseload_pct', 0):.1f}% of total energy
  Estimated Cost ............ ${e.get('estimated_cost_usd', 0):,.2f} USD

2. WATER PERFORMANCE
---------------------
  Total Consumption ......... {w.get('total_m3', 0):,.1f} m³ ({w.get('total_liters', 0):,.0f} L)
  Peak Flow Rate ............ {w.get('peak_m3_h', 0):.2f} m³/h
  Minimum Night Flow ........ {w.get('min_night_flow_m3_h', 0):.3f} m³/h (benchmark: < 0.15)
  Estimated Cost ............ ${w.get('estimated_cost_usd', 0):,.2f} USD

3. WASTE PERFORMANCE
---------------------
  Total Waste Generated ..... {r.get('total_waste_kg', 0):,.0f} kg ({r.get('total_waste_tonnes', 0):.2f} t)
  Diverted from Landfill .... {r.get('diverted_kg', 0):,.0f} kg
  Landfill Residual ......... {r.get('landfill_kg', 0):,.0f} kg
  Diversion Rate ............ {r.get('diversion_rate_pct', 0):.1f}% (status: {r.get('status', 'Tracking')})
  Estimated Hauling Cost .... ${r.get('estimated_hauling_cost_usd', 0):,.2f} USD

4. ANOMALY & RISK SUMMARY
--------------------------
  Total Incidents Flagged ... {len(filtered_anomalies)}
  Critical Severity ......... {crit_count}
  High Severity ............. {high_count}

5. PRIORITY RECOMMENDATIONS
-----------------------------
  1. [Energy] Verify HVAC thermostat setback schedules (16°C/28°C) during
     unoccupied windows (20:00–06:00) per ASHRAE Standard 90.1.

  2. [Water] Inspect restroom flushometer sensors and cooling tower makeup
     valves in facilities with night flow > 0.15 m³/h (EPA WaterSense).

  3. [Waste] Expand back-of-house organic composting in dining facilities
     to elevate diversion rate towards 75% Gold standard.

6. ASSUMPTIONS & RESPONSIBLE AI NOTICE
----------------------------------------
  Diagnostic hypotheses generated by machine-learning models (Isolation
  Forest anomaly detection + contextual baselines). ALL recommendations
  require human facility engineering verification prior to physical
  alterations. Cost/carbon estimates use standard factors and should be
  reviewed against actual utility billing data.

  Carbon factors: Grid 0.420 kg CO2e/kWh | Landfill 0.580 kg CO2e/kg
  Cost factors: Electricity $0.14/kWh | Water $3.80/m3 | Hauling $0.12/kg

  AI Provider: {_get_provider()}

================================================================================
EcoSync Resource Intelligence Platform v2.1
"""

    st.text_area("Report Preview", report_text, height=420)

    col1, col2 = st.columns(2)
    with col1:
        fname = f"EcoSync_Report_{building}_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"
        st.download_button("⬇ Download Report (.txt)", data=report_text,
                           file_name=fname, mime="text/plain",
                           use_container_width=True)
    with col2:
        st.info("💡 Tip: Open in any text editor or paste into a Word document for formatted distribution.")


def _get_provider() -> str:
    try:
        from src.ibm.watsonx_client import GraniteClient
        return GraniteClient().provider_status()
    except Exception:
        return "Local grounded fallback"
